CREATE TABLE PHOTO (
  PHOTO_ID INTEGER PRIMARY KEY NOT NULL IDENTITY,
  TITLE VARCHAR(50) NOT NULL,
  FILE_NAME VARCHAR(50) NOT NULL,
  FILE_DATA BLOB NOT NULL,
  IMAGE_MIME_TYPE VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(500),
  USER_NAME VARCHAR(50) NOT NULL,
  CREATE_DATE DATE NOT NULL,
  MODIFIED_DATE DATE
);
